// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel CSMain
#include "../Includes/Common.hlsl"
// Create a RenderTexture with enableRandomWrite flag and set it
// with cs.SetTexture
RWStructuredBuffer<EntityData> entityBuffer;
RWStructuredBuffer<EntityData> entity;
int index;
[numthreads(1,1,1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
    entity[0] = entityBuffer[index];
}
